### ISSUE TITLE
[Bug Report] Command parse get-new-animes --print-output is not working

### ISSUE THREAD

**Issue by EddieChoCho** [Lee-W/bahamut_ani_stat#7]
## Description
Command `parse get-new-animes --print-output` is not working correctly 

## bahamut_ani_stat version
0.3.0

## Steps to Reproduce
1. Enter command
        ```
        poetry run python bahamut_ani_stat/__main__.py parse get-new-animes --print-output
        ```

2. See error
         ```
         Either --print-out or --output-file needs to be provided
         ```

**Comment by Lee-W** [comment]
Thanks for reporting! I just confirmed both issues. Could you split them into separate ones? so that they can be tracked separately. Thanks1

**Comment by EddieChoCho** [comment]
> Thanks for reporting! I just confirmed both issues. Could you split them into separate ones? so that they can be tracked separately. Thanks1

Sure, here's the another issue: https://github.com/Lee-W/bahamut_ani_stat/issues/8
